name: 'Reviews Counter'
branding:
  color: 'green'
  icon: 'check-circle'
description: 'Collaborator pull request review counter.'
runs:
  main: 'dist/index.js'
  using: 'node12'
inputs:
  repo-token:
    description: 'GITHUB_TOKEN secret'
    required: true
outputs:
  REVIEW_COUNTER_APPROVED:
    description: 'Reviews allowing the pull request to merge.'
  REVIEW_COUNTER_CHANGES_REQUESTED:
    description: 'Reviews blocking the pull request from merging.'
  REVIEW_COUNTER_COMMENTED:
    description: 'Informational reviews.'
  REVIEW_COUNTER_DISMISSED:
    description: 'Reviews that have been dismissed.'
  REVIEW_COUNTER_PENDING:
    description: 'Reviews that have not yet been submitted.'
